FROM node:22-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY . .
RUN pnpm install
ARG VITE_PUBLIC_API_ENDPOINT
ARG VITE_PUBLIC_WEB_ENDPOINT
ARG VITE_PUBLIC_METABASE_ENDPOINT
ARG VITE_SENTRY_DSN
ARG VITE_SENTRY_ENVIRONMENT
ARG VITE_SENTRY_TRACES_SAMPLE_RATE
ENV VITE_PUBLIC_API_ENDPOINT=$VITE_PUBLIC_API_ENDPOINT \
    VITE_PUBLIC_WEB_ENDPOINT=$VITE_PUBLIC_WEB_ENDPOINT \
    VITE_PUBLIC_METABASE_ENDPOINT=$VITE_PUBLIC_METABASE_ENDPOINT \
    VITE_SENTRY_DSN=$VITE_SENTRY_DSN \
    VITE_SENTRY_ENVIRONMENT=$VITE_SENTRY_ENVIRONMENT \
    VITE_SENTRY_TRACES_SAMPLE_RATE=$VITE_SENTRY_TRACES_SAMPLE_RATE
RUN pnpm --filter hub build

FROM nginx:alpine
COPY nginx.hub.conf /etc/nginx/nginx.conf
COPY --from=builder /app/web/hub/dist /usr/share/nginx/html