FROM node:22-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.10.0 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY web ./web
RUN pnpm install --frozen-lockfile
ARG VITE_PUBLIC_API_ENDPOINT
ARG VITE_PUBLIC_WEB_ENDPOINT
ARG VITE_PUBLIC_SITE_NAME
ARG VITE_PUBLIC_SUPPORT_EMAIL
ARG VITE_PUBLIC_RPAY_FE_KEY
ARG VITE_PUBLIC_RPAY_SCRIPT
ARG VITE_SENTRY_DSN
ARG VITE_SENTRY_ENVIRONMENT
ARG VITE_SENTRY_TRACES_SAMPLE_RATE
ENV VITE_PUBLIC_API_ENDPOINT=$VITE_PUBLIC_API_ENDPOINT \
    VITE_PUBLIC_WEB_ENDPOINT=$VITE_PUBLIC_WEB_ENDPOINT \
    VITE_PUBLIC_SITE_NAME=$VITE_PUBLIC_SITE_NAME \
    VITE_PUBLIC_SUPPORT_EMAIL=$VITE_PUBLIC_SUPPORT_EMAIL \
    VITE_PUBLIC_RPAY_FE_KEY=$VITE_PUBLIC_RPAY_FE_KEY \
    VITE_PUBLIC_RPAY_SCRIPT=$VITE_PUBLIC_RPAY_SCRIPT \
    VITE_SENTRY_DSN=$VITE_SENTRY_DSN \
    VITE_SENTRY_ENVIRONMENT=$VITE_SENTRY_ENVIRONMENT \
    VITE_SENTRY_TRACES_SAMPLE_RATE=$VITE_SENTRY_TRACES_SAMPLE_RATE
RUN pnpm --filter mis build

FROM nginx:alpine
COPY nginx.mis.conf /etc/nginx/nginx.conf
COPY --from=builder /app/web/mis/dist /usr/share/nginx/html