export const PERMISSIONS = {
  READ_PROJECTS: "read_projects",
  READ_LABS: "read_labs",
  READ_USERS: "read_users",
  READ_MACHINES: "read_machines",
  READ_INVENTORY: "read_inventory",
  CREATE_LABS: "create_labs",
  CREATE_USERS: "create_users",
  CREATE_INVENTORY: "create_inventory",
  CREATE_MACHINES: "create_machines",
  CREATE_PROJECTS: "create_projects",
  UPDATE_LABS: "update_labs",
  UPDATE_USERS: "update_users",
  UPDATE_INVENTORY: "update_inventory",
  UPDATE_MACHINES: "update_machines",
  UPDATE_PROJECTS: "update_projects",
  DELETE_LABS: "delete_labs",
  DELETE_USERS: "delete_users",
  DELETE_INVENTORY: "delete_inventory",
  DELETE_MACHINES: "delete_machines",
  DELETE_PROJECTS: "delete_projects",
  APPROVE_INVENTORY: "approve_inventory",
  APPROVE_MACHINES: "approve_machines",
  APPROVE_PROJECTS: "approve_projects",

  CREATE_ATTENDANCE: "create_attendance",
  UPDATE_ATTENDANCE: "update_attendance",
  DELETE_ATTENDANCE: "delete_attendance",
  READ_ATTENDANCE: "read_attendance",
  APPROVE_ATTENDANCE: "approve_attendance",
  SUPER_ADMIN: "super_admin",

  READ_ORGANISATIONS: "read_organisations",
  UPDATE_ORGANISATIONS: "update_organisations",
  CREATE_ORGANISATIONS: "create_organisations",
  DELETE_ORGANISATIONS: "delete_organisations",
} as const;

export type IPermissions = keyof typeof PERMISSIONS;
